### ISSUE TITLE
Hyperlink is missing below the picture

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#87]
### Steps to reproduce:

1)Navigate to the following page: https://planetcassandra.org/
2)Click at "Resources" button at the top of the page
3)Click at the hyperlink named "Architect’s Guide to Using NoSQL for Real-time AI: Part 1" 
4)After you are navigated at the following page https://planetcassandra.org/leaf/architect-s-guide-to-using-nosql-for-real-time-ai-part-1/ observe below the picture 

### Actual Results:
Hyperlink link is missing 
### Expected Results:
Hyperlink is below the picture and its functional
### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/245126629-73b47d31-3e95-44d7-8c39-8003515e4c1e.png)

**Comment by JovanTanchevski** [comment]
Taking a look at it now

**Comment by JovanTanchevski** [comment]
At our code, we have a function that is - 
```
// Check if the articleUrl starts with "https://planetcassandra"
  if (articleUrl.startsWith("https://planetcassandra.org") || articleUrl.startsWith("https://www.youtube.com")) {
    return null; // Hide the whole component
  }
``` 
which basically hides the whole component, as of this hyperlink, the link is `https://planetcassandra.org/post/architects-guide-to-using-nosql-for-real-time-ai-part-1/` meaning that this component will not be shown because the hyperlink is part of planetcassandra.org
